name: recourse_fare
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scikit-learn
  - pytorch
  - pandas
  - pyyaml
  - mpi4py
  - colorama
  - tqdm
  - pip
  - dill
  - pip:
    - tensorboardX