name: rl_mcts
channels:
  - defaults
dependencies:
    - python=3.9
  - numpy
  - torchaudio
  - torchvision
  - cpuonly
  - pytorch
  - pandas
  - pyyaml
  - mpi4py
  - colorama
  - pip
  - pip:
    - tensorboardX-2.6