general:
  seed: 2021
  save_model: true
  save_model_dir: "ignore/models"
  save_model_name: "test_experiment"
  tensorboard: true
  tensorboard_dir: "ignore/runs"

# Specify training parameters
training:

  num_iterations: 20
  num_episodes_per_iteration: 10

  mcts:
    name: "rl_mcts.core.mcts.MCTS"
    configuration_parameters:
      exploration: true
      number_of_simulations: 10
      dir_epsilon: 0.03
      dir_noise: 0.3
      level_closeness_coeff: 3.0
      level_0_penalty: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.97

  trainer:
    batch_size: 40

  curriculum_statistics:
    moving_average: 0.99

  replay_buffer:
    size: 200
    sampling_correct_probability: 0.8
    sampling_from_failed_states: 0.3 # Still need to be implemented

# Environment of this experiment
environment:
  name: "rl_mcts.example.mock_env.MockEnv"

  # Encoder for the environment of this experiment
  encoder:
    name: "rl_mcts.example.mock_env.MockEnvEncoder"
    configuration_parameters:
      encoding_dim: 20

# Policy used for this experiment
policy:
  name: "rl_mcts.core.agents.policy.Policy"
  hidden_size: 50
  embedding_dim: 100
  encoding_dim: 20 # This needs to be equal to the encoder embedding_dim

validation:
  dataset_name: "mock_env"
  iterations: 100

  mcts:
    name: "rl_mcts.core.mcts.MCTS"
    configuration_parameters:
      exploration: false
      number_of_simulations: 5
      dir_epsilon: 0.03
      dir_noise: 0.3
      level_closeness_coeff: 3.0
      level_0_penalty: 1.0
      qvalue_temperature: 1.0
      temperature: 1.3
      c_puct: 0.5
      gamma: 0.97

  #environment: # Additional parameters for the validation environment
    #configuration_parameters:
      #data: "data/test.csv"
  save_results: "ignore"
  save_results_name: "results"